# Generated by Django 5.1.3 on 2024-11-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_uniquebook_detection"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniquebook",
            name="cropped_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="unique_books/cropped/"
            ),
        ),
        migrations.AddField(
            model_name="uniquebook",
            name="rotated_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="unique_books/rotated/"
            ),
        ),
        migrations.AlterField(
            model_name="uniquebook",
            name="detection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unique_books",
                to="books.detection",
            ),
        ),
    ]
