# Generated by Django 5.1.3 on 2024-12-02 18:15

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_uniquebook_cropped_image_uniquebook_rotated_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookDetection",
        ),
        migrations.AlterModelOptions(
            name="uniquebook",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="detectedbook",
            name="cropped_image",
            field=models.ImageField(upload_to=books.models.upload_to_common_dir),
        ),
        migrations.AlterField(
            model_name="detectedbook",
            name="rotated_image",
            field=models.ImageField(upload_to=books.models.upload_to_common_dir),
        ),
        migrations.AlterField(
            model_name="detection",
            name="uploaded_image",
            field=models.ImageField(upload_to=books.models.upload_to_common_dir),
        ),
        migrations.AlterField(
            model_name="uniquebook",
            name="cropped_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=books.models.upload_to_common_dir
            ),
        ),
        migrations.AlterField(
            model_name="uniquebook",
            name="rotated_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=books.models.upload_to_common_dir
            ),
        ),
    ]
