# Generated by Django 5.1.3 on 2024-12-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
