# Generated by Django 5.1.3 on 2024-12-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
